### ISSUE TITLE
prohibitive delays in functioning of the PAT-OKC

### ISSUE THREAD

**Issue by magpie81** [meitar/pat-okcupid#14] opened 2013-12-09 06:51 UTC
Hi maymay, 

Here's a documentation of my problem(s) with PAT-OKC. As I said on Facebook, I can't rule out that I'm doing something wrong here, so let me know if I'm doing something wrong. 

I'm going to address how it's working right now, in the hopes that this is the most helpful information. I'm going to tackle this by explaining my steps, since I can't begin to draw any conclusions from the resulting behavior. 

I'm on a netbook running Windows 7, chrome browser, with tampermonkey extension. I first installed PAT-OKC months ago. 

My tampermonkey was off so I turned it on. It appears to no longer have PAT-OKC scripts.
![image](https://f.cloud.github.com/assets/5397612/1702392/61603d20-6091-11e3-9ebb-d6bd8bfd5d36.png)
I refreshed my tab open to OKC and the script appears to have kicked in. 
![image](https://f.cloud.github.com/assets/5397612/1702411/cf9ad304-6091-11e3-826d-ea992283e0c9.png)
And my system has now slowed down considerably. Pasting that last image into this field nearly crashed this tab. Forging ahead...
I click on "Resume PAT-OKC"
The page appears to have fully loaded.
I go to scroll down to view what's on the page... and it goes unresponsive:
![image](https://f.cloud.github.com/assets/5397612/1702453/403dc704-6094-11e3-8ac1-93584a8d739d.png)
I take a screen capture, come back to the github tab and paste it. 
It causes the github tab to go unresponsive.
I close the OKC tab, turn off tampermonkey, close unnecessary programs and tabs. 
I wait a long ass time. (5-10min?) Somehow github comes back to being responsive so that I'm able to continue writing this. [I'm now keeping a copy of this in a text file in case it thoroughly crashes.]
I open a new tab and navigate to OKC.
I turn back on tampermonkey.
I reload the page and the PAT-OKC comes back online... although it now reads "4" where it used to read "5"
![okccrash2](https://f.cloud.github.com/assets/5397612/1702646/f3aa17a8-609d-11e3-93c5-32f1d0552ee5.png)
after trying to paste the screenshot in github the page went unresponsive. I waited a long time, and eventually the whole browser shut down. 
Seems like I cannot paste images into git hub while also using OKC, so I'm closing github and keeping notes in a text file. of course in the process of closing the github tab the whole browser crashed again. 
Reopened the browser. 
Went to OKC tab.
Followed the "Resume PAT-OKC" link.
Tab went unresponsive. 
Killed it and reloaded.
I still can't scroll down the page and it keeps popping up "page is unresponsive" messages which I tell it to "wait" but it pops up again. 
I've now spent two episodes of Voyager doing documentation (well, really, I guess it's not been documentation as much as frustrated waiting.)
Somehow the page has finally let me scroll to where I can see the question.
I can't scroll around the page freely, so I answer the question and click "submit". I don't snag a screen shot because I'm afraid of breathing on this house of cards.
It appears to have loaded the next question, however I cannot scroll down the page to read it without it popping up a "page unresponsive" message.
I give it a couple tries of waiting out the unresponsiveness and now I'm calling it quits. I close the OKC tab and navigate back to github to file this report. 

This has been a particularly frustrating episode of trying to get PAT-OKC to work. My memories of past experiences are that it takes a couple "wait"s of the page freezing before I can answer the question; rinse and repeat for each question. I've made a couple go's at getting through the questions, but it seems like it may not be retaining all the answers? I spent many hours (because of the loading delays) answering questions when I first installed it. I even thought maybe it'd segued into the general pool of questions, but when I came back (I can't remember if it cashed or if I left it voluntarily) I still had questions to do. 

To me this doesn't make any sense, but maybe you have some ideas?

**Comment by meitar** [comment] 2017-04-16 22:22
This seems like it's ultimately a duplicate of #13.

**Closed by meitar** 2017-04-16 22:22 UTC
