### ISSUE TITLE
Issue with red outline disappearing on matches page

### ISSUE THREAD

**Issue by thespiansmc** [meitar/pat-okcupid#12] opened 2013-07-19 06:59 UTC
I noticed something odd and replicable in the OKC-PAT. When I look at 'matches' the first time, it has a redbar about people with issues. This afternoon I clicked through to see what the issue is (most often it's that they think drinking too much is an excuse to do something stupid). If I go back to 'matches' again (back button), afterwards, even if they're still on the page, the line is gone. However they still have the bar around them in the sidebar 'recently looked at' section. They will also still have the flag on their page, and will have the bar if I find them elsewhere on OKC; it just disappears on the matches page. I tried reloading the page, and it did not reappear, but I figured it might just be a onetime thing, but it just did it a second time with another match so I figured I'd mention it. I am using Firefox 22.0 on Windows 7.

**Comment by meitar** [comment] 2017-04-16 22:20
This is a duplicate of #21.

**Closed by meitar** 2017-04-16 22:20 UTC
